main_url: https://pwindows.qzz.io

navigation:
  - translation_key: about
    path: /about
    icon: /assets/mojang/svg/icons/book.png
  - translation_key: news
    path: /articles
    icon: /assets/mojang/Invicon_Map.png
  - translation_key: staff
    path: /staff
    icon: /assets/mojang/svg/icons/color-two-players.svg
  - translation_key: departments
    path: /departments/
    icon: /assets/mojang/svg/icons/color-chest.svg
  - translation_key: games
    path: /games
    icon: /assets/icons/controller.png

footer_sections:
  - translation_key: games
    column_class: footer-column-center
    path: /games
    links:
      - translation_key: sacred-cubes
        path: /games/sacred-cubes
      - translation_key: obby-of-dominance
        path: /games/obby-of-dominance
  - translation_key: departments
    column_class: footer-column-departments
    show_language: true
    path: /departments/
    links:
      - translation_key: mcd
        path: /departments/minecraft
      - translation_key: rd
        path: /departments/roblox
      - translation_key: ud
        path: /departments/unity
  - translation_key: support
    column_class: footer-column-right
    show_shop: true
    url: https://support.pwindows.qzz.io
    links:
      - translation_key: feedback
        path: /feedback
      - translation_key: sitemap
        path: /sitemap
      - translation_key: contact
        path: /contact
      - translation_key: staff
        path: /staff

links:
  support: https://support.pwindows.qzz.io
  shop: https://shop.pwindows.qzz.io
  discord: https://discord.pwindows.qzz.io/
  youtube: https://www.youtube.com/@PWindows
  twitter: https://x.com/pwindowsz
  site_logo: /assets/PWindows.png
